import React from 'react'
import  hero from '../../assets/hero.png'
const One = () => {
  return (
    <div style={{alignItems:"center",width:"1200px",marginLeft:"auto",marginRight:"auto",textAlign:"center"}}>
      <img src={hero} alt=""  width={'60px'}/>
      <h1 style={{fontFamily:"sans-serif",fontStyle:"italic"}}>Gussie Singleton</h1>
      <p style={{fontFamily:"sans-serif",fontStyle:"italic",width:"1200px",textAlign:"left"} }>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa eaque maiores eos soluta placeat, facilis consequatur voluptatum minus aliquam unde quibusdam expedita provident ullam libero maxime saepe beatae similique corporis! Veniam facilis sint commodi temporibus? Ea sint amet nemo et doloremque maxime? Non facilis voluptate enim neque, architecto rem distinctio libero maxime perferendis vitae officia ipsa consequatur unde quis dolores sit ducimus vel illum voluptates beatae cumque corporis optio amet ratione! Tempora laudantium, debitis quasi id pariatur quisquam et sed dicta provident assumenda alias autem cum sit ad nobis facere? Recusandae nesciunt sit quidem tenetur amet nemo aperiam exercitationem temporibus est odit eius quo asperiores debitis in consequatur mollitia, blanditiis nostrum perferendis obcaecati magnam, saepe, voluptas dicta. Excepturi provident natus repellendus sed a laborum nemo fugit sapiente nobis! Hic veniam dicta reiciendis sint repellendus accusamus nesciunt consequatur vero neque quia non eaque rem eius quasi labore perferendis, totam rerum explicabo quisquam quidem dolorem ut incidunt? Incidunt officia ea fuga reiciendis facilis modi cum, saepe assumenda blanditiis odio. Recusandae alias eum nam, dolorem quos accusantium autem voluptate. Quam illo eaque esse porro minus aut nesciunt totam quia consequatur odit! Velit, quia recusandae harum tempora esse provident doloribus repellat saepe nisi rerum explicabo sunt doloremque nam magni porro ab corrupti quo obcaecati? Enim quidem rerum nobis sapiente laboriosam, repellendus error recusandae exercitationem nemo voluptatibus, modi neque molestiae hic ea natus eveniet? Temporibus culpa laboriosam a suscipit aut labore itaque voluptatibus nam eos nihil eius modi eaque ad unde velit excepturi maxime aliquid omnis officiis, nostrum, facere ipsa minus totam. Perspiciatis architecto at sapiente a laborum dolores vero sed incidunt accusamus ex itaque optio, dolore earum quam ullam est labore, ea, consectetur laboriosam ipsam necessitatibus atque! A odio nostrum et aperiam distinctio sunt cumque accusantium animi, quod atque quis, adipisci, maiores iure qui?aperiam distinctio sunt cumque accusantium animi, quod atque quis, adipisci, maiores iure qui? quod atque quis</p>
    </div>
  )
}

export default One
